---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  # out.width = "100%",
  fig.width = 6,
  fig.height = 4,
  message = FALSE
)
Sys.setlocale("LC_TIME", "C")
```

# prophetExt: Additional Features for Prophet Time-Series Forecasting

<!-- badges: start -->
<!-- badges: end -->

## Installation

You can install the development version of prophetExt like so:

``` r
remotes::install_github("hoxo-m/prophetExt")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
df <- read.csv("https://raw.githubusercontent.com/facebook/prophet/master/examples/example_wp_log_R_outliers2.csv", skip = 337, col.names = c("ds", "y"))
head(df)
```

```{r}
library(prophet)

model <- prophet(df)
df_future <- make_future_dataframe(model, 365)
fore <- predict(model, df_future)

plot(model, fore)
```

```{r}
library(prophetExt)

outliers <- detect_outliers(model)

plot(model, fore) + autolayer(outliers)
```

```{r, fig.width=10, fig.height=7.5}
calendar_plot(outliers)
```

```{r}
df$y[df$ds %in% outliers$ds] <- NA

model <- prophet(df)
df_future <- make_future_dataframe(model, 365)
fore <- predict(model, df_future)

plot(model, fore)
```
